// storybooks/svelte/Arguments.svelte
<script>
  import heelflip from '../../src/svelte';

  const getCharacters = async ({ username }) =>
    fetch(`https://rickandmortyapi.com/api/character?name=${username}`).then((res) => res.json());

  let username = 'rick';
  const store = heelflip.fetch(['characters', [{ username }]], getCharacters);

  function handleClickFetch() {
    store.invoke({ username });
  }

  $: {
    console.log($store);
  }
</script>

<div>
  <input bind:value={username} />
  <button on:click={handleClickFetch}>
    {#if $store.isReloading}Fetching...{:else}Fetch{/if}
  </button>
  {#if $store.isLoading}
    <p>Loading...</p>
  {/if}
  {#if $store.isSuccess}
    <ul>
      {#each $store.response.results as character}
        <li>{character.name}</li>
      {/each}
    </ul>
  {/if}
  {#if $store.isError}
    <p>Awwies</p>
  {/if}
</div>

// storybooks/react/Arguments.js
import React from 'react';
import heelflip from '../../src/react';

export default function Basic() {
  const [username, setUsername] = React.useState('');

  const getCharacters = React.useCallback(
    async ({ username = 'rick' } = {}) => fetch(`https://rickandmortyapi.com/api/character?name=${username}`).then((res) => res.json()),
    []
  );
  const record = heelflip.useFetch('characters', getCharacters);

  function handleClickFetch() {
    record.invoke({ username });
  }

  return (
    <div>
      <input onChange={e => setUsername(e.target.value)} value={username} />
      <button onClick={handleClickFetch}>Fetch</button>
      <h1>Characters</h1>
      {record.isLoading && <p>Loading...</p>}
      {record.isSuccess && (
        <ul>
          {record.response.results.map((character, i) => (
            <li key={i}>{character.name}</li>
          ))}
        </ul>
      )}
      {record.isError && <p>Awwies</p>}
    </div>
  );
}
