// src/__stories__/CustomConfig.svelte
<script>
  import heelflip from '../svelte';

  heelflip.setConfig({
    timeToSlowConnection: 1000,
  });

  const getThing = async () => new Promise((res) => setTimeout(() => res('This is a slow response'), 3000));
  const store = heelflip.deferredFetch('thing', getThing);

  $: {
    console.log($store);
  }
</script>

<div>
  {#if $store.isIdle}<button on:click={store.invoke}>Load</button>{/if}
  {#if $store.isLoading}
    <p>Loading...</p>
    {#if $store.isLoadingSlow}
      <p>Taking a while...</p>
    {/if}
  {/if}
  {#if $store.isSuccess}
    {#each $store.response as message}{message}{/each}
  {/if}
  {#if $store.isError}
    <p>Awwies</p>
  {/if}
</div>

// storybooks/react/CustomConfig.js
import React from 'react';
import heelflip, { ConfigProvider } from '../../src/react';

function CustomConfig() {
  const getResource = React.useCallback(
    async () => new Promise((res) => setTimeout(() => res('This is a slow response'), 3000)),
    []
  );
  const record = heelflip.useDeferredFetch('resource', getResource);

  return (
    <div>
      {record.isIdle && <button onClick={record.invoke}>Load</button>}
      {record.isLoading && <p>Loading...</p>}
      {record.isLoadingSlow && <p>Taking a while...</p>}
      {record.isSuccess && record.response}
    </div>
  );
}

export default function Example() {
  return (
    <ConfigProvider config={{ timeToSlowConnection: 1000 }}>
      <CustomConfig />
    </ConfigProvider>
  );
}
