// storybooks/react/Basic.js
import React from 'react';
import heelflip from '../../src/react';

export default function Basic() {
  const getCharacters = React.useCallback(
    async () => fetch('https://rickandmortyapi.com/api/character?name=rick').then((res) => res.json()),
    []
  );
  const record = heelflip.useFetch('characters', getCharacters);
  return (
    <div>
      <h1>Characters</h1>
      {record.isLoading && <p>Loading...</p>}
      {record.isSuccess && (
        <ul>
          {record.response.results.map((character, i) => (
            <li key={i}>{character.name}</li>
          ))}
        </ul>
      )}
      {record.isError && <p>Awwies</p>}
    </div>
  );
}

// src/__stories__/Basic.svelte
<script>
  import heelflip from '../svelte';

  const getCharacters = async () =>
    fetch('https://rickandmortyapi.com/api/character?name=rick').then((res) => res.json());
  const store = heelflip.fetch('characters', getCharacters);

  $: {
    console.log($store);
  }
</script>

<div>
  <h1>Characters</h1>
  {#if $store.isLoading}
    <p>Loading...</p>
  {/if}
  {#if $store.isSuccess}
    <ul>
      {#each $store.response.results as character}
        <li>{character.name}</li>
      {/each}
    </ul>
  {/if}
  {#if $store.isError}
    <p>Awwies</p>
  {/if}
</div>
