// storybooks/react/Broadcast.js
import React from 'react';
import heelflip from '../../src/react';

export default function BasicDeffered() {
  const getCharacters = React.useCallback(
    async () => fetch('https://rickandmortyapi.com/api/character?name=rick').then((res) => res.json()),
    []
  );

  const firstRecord = heelflip.useFetch('characters', getCharacters, { enabled: false });
  const secondRecord = heelflip.useFetch('characters', getCharacters, { enabled: false });
  const thirdRecord = heelflip.useFetch('characters', getCharacters, { enabled: false });

  return (
    <div>
      <p>
        When we fetch the first characters store, it will also fetch the second and third store as it will broadcast the
        successful response across all consumer stores with context "characters".
      </p>
      <button>Fetch</button>
      <div>
        <h1>Characters (first record)</h1>
        {firstRecord.isLoading && <p>Loading...</p>}
        {firstRecord.isSuccess && (
          <ul>
            {firstRecord.response.results.map((character, i) => (
              <li key={i}>{character.name}</li>
            ))}
          </ul>
        )}
        {firstRecord.isError && <p>Awwies</p>}
      </div>
      <div>
        <h1>Characters (second record)</h1>
        {secondRecord.isLoading && <p>Loading...</p>}
        {secondRecord.isSuccess && (
          <ul>
            {secondRecord.response.results.map((character, i) => (
              <li key={i}>{character.name}</li>
            ))}
          </ul>
        )}
        {secondRecord.isError && <p>Awwies</p>}
      </div>
      <div>
        <h1>Characters (third record)</h1>
        {thirdRecord.isLoading && <p>Loading...</p>}
        {thirdRecord.isSuccess && (
          <ul>
            {thirdRecord.response.results.map((character, i) => (
              <li key={i}>{character.name}</li>
            ))}
          </ul>
        )}
        {thirdRecord.isError && <p>Awwies</p>}
      </div>
    </div>
  );
}

// src/__stories__/Broadcast.svelte
<script>
  import heelflip from '../svelte';

  const getRepos = async () => fetch('https://rickandmortyapi.com/api/character?name=rick').then((res) => res.json());

  const firstStore = heelflip.fetch('characters', getRepos, { enabled: false });
  const secondStore = heelflip.fetch('characters', getRepos, { enabled: false });
  const thirdStore = heelflip.fetch('characters', getRepos, { enabled: false });
</script>

<div>
  <p>
    When we fetch the first characters store, it will also fetch the second and third store as it will broadcast the
    successful response across all consumer stores with context "characters".
  </p>

  <button on:click={() => firstStore.invoke()}>Fetch first store</button>

  <h1>Characters (first store)</h1>
  {#if $firstStore.isLoading}
    <p>Loading...</p>
  {/if}
  {#if $firstStore.isSuccess}
    <ul>
      {#each $firstStore.response.results as character}
        <li>{character.name}</li>
      {/each}
    </ul>
  {/if}
  {#if $firstStore.isError}
    <p>Awwies</p>
  {/if}
</div>

<div>
  <h1>Characters (second store)</h1>
  {#if $secondStore.isLoading}
    <p>Loading...</p>
  {/if}
  {#if $secondStore.isSuccess}
    <ul>
      {#each $secondStore.response.results as character}
        <li>{character.name}</li>
      {/each}
    </ul>
  {/if}
  {#if $secondStore.isError}
    <p>Awwies</p>
  {/if}
</div>

<div>
  <h1>Characters (third store)</h1>
  {#if $thirdStore.isLoading}
    <p>Loading...</p>
  {/if}
  {#if $thirdStore.isSuccess}
    <ul>
      {#each $thirdStore.response.results as character}
        <li>{character.name}</li>
      {/each}
    </ul>
  {/if}
  {#if $thirdStore.isError}
    <p>Awwies</p>
  {/if}
</div>
